### ISSUE TITLE
Error when accessing container via Apache drill jdbc

### ISSUE THREAD

**Issue by amalic** [mkieboom/apache-drill-docker#1]
I am getting this error when trying to access your container via Drill JDBC (i also tried it with the most current version of drill 1.13)

Here's my jdbc-properties (I linked drill via "--link \<drill-container-name\>:drill"
```
connectionURL = jdbc:drill:drillbit=drill:31010
user = admin
password = admin
```

And here the exception
```
ERROR R2RMLProcessor:94 - Error connecting to database.
java.sql.SQLException: Failure in creating DrillConnectionImpl: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'drill.memory'
        at org.apache.drill.jdbc.impl.DrillConnectionImpl.<init>(DrillConnectionImpl.java:183)
        at org.apache.drill.jdbc.impl.DrillJdbc41Factory.newDrillConnection(DrillJdbc41Factory.java:73)
        at org.apache.drill.jdbc.impl.DrillFactory.newConnection(DrillFactory.java:69)
        at org.apache.calcite.avatica.UnregisteredDriver.connect(UnregisteredDriver.java:138)
        at org.apache.drill.jdbc.Driver.connect(Driver.java:72)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:208)
        at r2rml.engine.R2RMLProcessor.createDatabaseConnection(R2RMLProcessor.java:90)
        at r2rml.engine.R2RMLProcessor.execute(R2RMLProcessor.java:39)
        at r2rml.Main.main(Main.java:59)
Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'drill.memory'
        at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:115)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:138)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:142)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:150)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:155)
        at com.typesafe.config.impl.SimpleConfig.getConfigNumber(SimpleConfig.java:170)
        at com.typesafe.config.impl.SimpleConfig.getNumber(SimpleConfig.java:176)
        at com.typesafe.config.impl.SimpleConfig.getLong(SimpleConfig.java:187)
        at org.apache.drill.common.config.NestedConfig.getLong(NestedConfig.java:101)
        at org.apache.drill.common.config.DrillConfig.getLong(DrillConfig.java:43)
        at org.apache.drill.exec.memory.RootAllocatorFactory.newRoot(RootAllocatorFactory.java:40)
        at org.apache.drill.jdbc.impl.DrillConnectionImpl.<init>(DrillConnectionImpl.java:156)
        ... 9 more
```

**Comment by amalic** [comment]
I fixed it myself. Issue was my [maven fat-jar build](https://github.com/amalic/r2rml/blob/master/pom.xml) it was missing a config file.

**Comment by VenkatSampath** [comment]
Hi amalic 
In one of my project I am trying to connect with Apache drill using jdbc ..we are able to do it so while executing from eclipse .but when we convert it to executable jar we get drill memory error .. 

Dependency jars are kept local..kindly help us to resolve the issue 

Thanks
Venkat
